### CONFIGURATED BY Vagrantfile.j2 and j2cli
unless Vagrant.has_plugin?("vagrant-vbguest")
  puts 'Installing vagrant-vbguest Plugin...'
  system('vagrant plugin install vagrant-vbguest')
end

unless Vagrant.has_plugin?("vagrant-hostmanager")
  puts 'Installing vagrant-hostmanager Plugin...'
  system('vagrant plugin install vagrant-hostmanager')
end

unless Vagrant.has_plugin?("vagrant-ansible-local")
  puts 'Installing vagrant-ansible-local Plugin...'
  system('vagrant plugin install vagrant-ansible-local')
end

Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vbguest.auto_update = false

    ### CONFIG node0 VM GENERATED
    config.vm.define "node0" do |node0|
      node0.vm.box = "centos/stream8"
      node0.vm.hostname = 'node0.vm'
      node0.vm.network "private_network", :type => 'static', :adapter => 2, ip: "192.168.56.100", use_dhcp_assigned_default_route: true
      
      node0.hostmanager.enabled = true
      node0.hostmanager.manage_host = false
      node0.hostmanager.manage_guest = true
      node0.hostmanager.ignore_private_ip = false
      node0.hostmanager.include_offline = true
      node0.hostmanager.aliases = %w(node0.localdomain node0.local node0.vm)

      node0.vm.provider "virtualbox" do |vb|
         vb.name="node0"
         vb.gui = false
         vb.memory = 1024
         vb.cpus = 1
         vb.customize ["modifyvm", :id, "--groups", "/VagrantVms/MySQL/mysql"]
      end
      
      node0.vm.provision :hostmanager
      node0.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("././id_rsa_vm.pub").first.strip
        ssh_priv_key = File.read("././id_rsa_vm")
        s.inline = <<-SHELL
            mkdir -p /root/.ssh
            echo "#{ssh_pub_key}"  | tee -a /home/vagrant/.ssh/authorized_keys
            echo "#{ssh_pub_key}"  | tee -a /root/.ssh/authorized_keys
            echo "#{ssh_priv_key}" | tee /home/vagrant/.ssh/id_rsa
            echo "#{ssh_priv_key}" | tee /root/.ssh/id_rsa
            chmod 600 /root/.ssh/id_rsa /home/vagrant/.ssh/id_rsa
            chown vagrant. /home/vagrant/.ssh/id_rsa
        SHELL
      end
      
    end
    

    ### CONFIG node1 VM GENERATED
    config.vm.define "node1" do |node1|
      node1.vm.box = "centos/stream8"
      node1.vm.hostname = 'node1.vm'
      node1.vm.network "private_network", :type => 'static', :adapter => 2, ip: "192.168.56.101", use_dhcp_assigned_default_route: true
      
      node1.hostmanager.enabled = true
      node1.hostmanager.manage_host = false
      node1.hostmanager.manage_guest = true
      node1.hostmanager.ignore_private_ip = false
      node1.hostmanager.include_offline = true
      node1.hostmanager.aliases = %w(node1.localdomain node1.local node1.vm)

      node1.vm.provider "virtualbox" do |vb|
         vb.name="node1"
         vb.gui = false
         vb.memory = 1024
         vb.cpus = 1
         vb.customize ["modifyvm", :id, "--groups", "/VagrantVms/MySQL/mysql"]
      end
      
      node1.vm.provision :hostmanager
      node1.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("././id_rsa_vm.pub").first.strip
        ssh_priv_key = File.read("././id_rsa_vm")
        s.inline = <<-SHELL
            mkdir -p /root/.ssh
            echo "#{ssh_pub_key}"  | tee -a /home/vagrant/.ssh/authorized_keys
            echo "#{ssh_pub_key}"  | tee -a /root/.ssh/authorized_keys
            echo "#{ssh_priv_key}" | tee /home/vagrant/.ssh/id_rsa
            echo "#{ssh_priv_key}" | tee /root/.ssh/id_rsa
            chmod 600 /root/.ssh/id_rsa /home/vagrant/.ssh/id_rsa
            chown vagrant. /home/vagrant/.ssh/id_rsa
        SHELL
      end
      
    end
    

    ### CONFIG node2 VM GENERATED
    config.vm.define "node2" do |node2|
      node2.vm.box = "centos/stream8"
      node2.vm.hostname = 'node2.vm'
      node2.vm.network "private_network", :type => 'static', :adapter => 2, ip: "192.168.56.102", use_dhcp_assigned_default_route: true
      
      node2.hostmanager.enabled = true
      node2.hostmanager.manage_host = false
      node2.hostmanager.manage_guest = true
      node2.hostmanager.ignore_private_ip = false
      node2.hostmanager.include_offline = true
      node2.hostmanager.aliases = %w(node2.localdomain node2.local node2.vm)

      node2.vm.provider "virtualbox" do |vb|
         vb.name="node2"
         vb.gui = false
         vb.memory = 1024
         vb.cpus = 1
         vb.customize ["modifyvm", :id, "--groups", "/VagrantVms/MySQL/mysql"]
      end
      
      node2.vm.provision :hostmanager
      node2.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("././id_rsa_vm.pub").first.strip
        ssh_priv_key = File.read("././id_rsa_vm")
        s.inline = <<-SHELL
            mkdir -p /root/.ssh
            echo "#{ssh_pub_key}"  | tee -a /home/vagrant/.ssh/authorized_keys
            echo "#{ssh_pub_key}"  | tee -a /root/.ssh/authorized_keys
            echo "#{ssh_priv_key}" | tee /home/vagrant/.ssh/id_rsa
            echo "#{ssh_priv_key}" | tee /root/.ssh/id_rsa
            chmod 600 /root/.ssh/id_rsa /home/vagrant/.ssh/id_rsa
            chown vagrant. /home/vagrant/.ssh/id_rsa
        SHELL
      end
      
    end
    




    ### CONFIG loadb0 VM GENERATED
    config.vm.define "loadb0" do |loadb0|
      loadb0.vm.box = "centos/stream8"
      loadb0.vm.hostname = 'loadb0.vm'
      loadb0.vm.network "private_network", :type => 'static', :adapter => 2, ip: "192.168.56.110", use_dhcp_assigned_default_route: true
      
      loadb0.hostmanager.enabled = true
      loadb0.hostmanager.manage_host = false
      loadb0.hostmanager.manage_guest = true
      loadb0.hostmanager.ignore_private_ip = false
      loadb0.hostmanager.include_offline = true
      loadb0.hostmanager.aliases = %w(loadb0.localdomain loadb0.local loadb0.vm)

      loadb0.vm.provider "virtualbox" do |vb|
         vb.name="loadb0"
         vb.gui = false
         vb.memory = 1024
         vb.cpus = 1
         vb.customize ["modifyvm", :id, "--groups", "/VagrantVms/MySQL/loadbalancer"]
      end
      
      loadb0.vm.provision :hostmanager
      loadb0.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("././id_rsa_vm.pub").first.strip
        ssh_priv_key = File.read("././id_rsa_vm")
        s.inline = <<-SHELL
            mkdir -p /root/.ssh
            echo "#{ssh_pub_key}"  | tee -a /home/vagrant/.ssh/authorized_keys
            echo "#{ssh_pub_key}"  | tee -a /root/.ssh/authorized_keys
            echo "#{ssh_priv_key}" | tee /home/vagrant/.ssh/id_rsa
            echo "#{ssh_priv_key}" | tee /root/.ssh/id_rsa
            chmod 600 /root/.ssh/id_rsa /home/vagrant/.ssh/id_rsa
            chown vagrant. /home/vagrant/.ssh/id_rsa
        SHELL
      end
      
    end
    


end