version: '3.7'

services:
  prometheus:
    image: prom/prometheus:main
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:main-ubuntu
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret # Change this to a secure password
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
