#!/bin/bash
### SCRIPT BASH GENERATED BY mygenconf.py at {datetime}
source ../profile
lcreate jmr_app1 eixo1hoo7Goo7suu9v $(cat ./id_rsa.pub) application webapps linux
lcreate jmr_proxy eixo1hoo7Goo7suu9v $(cat ./id_rsa.pub) proxy linux
lcreate jmr_dbsrv1 eixo1hoo7Goo7suu9v $(cat ./id_rsa.pub) mariadb db database linux
lcreate jmr_dbsrv2 eixo1hoo7Goo7suu9v $(cat ./id_rsa.pub) mariadb db database linux
lcreate jmr_dbsrv3 eixo1hoo7Goo7suu9v $(cat ./id_rsa.pub) mariadb db database linux
lcreate jmr_manager1 eixo1hoo7Goo7suu9v $(cat ./id_rsa.pub) control management linux
