#!/bin/bash
### SCRIPT BASH GENERATED BY mygenconf.py at {datetime}
source ../profile
ldelete jmr_app1
ldelete jmr_proxy
ldelete jmr_dbsrv1
ldelete jmr_dbsrv2
ldelete jmr_dbsrv3
ldelete jmr_manager1
