[package]
name = "myuser"
version = "0.0.1"
edition = "2021"

[dependencies]
colored = "2.1.0"
dotenv = "0.15.0"
fern = { version = "0.6.2", features = ["colored", "chrono"] }
humantime = "2.1.0"
log = "0.4.20"
mysql = "24.0.0"
[[bin]]
name = "myuser"
path = "src/main.rs"
