#!/bin/bash

# Configuration
MASTER_IP="10.5.0.11"
MASTER_PORT=3411
SLAVE1_PORT=3412
SLAVE2_PORT=3413
USER="root"
PASS="rootpass"
REPLI_USER="repli_user"
REPLI_PASS="replipass"

echo "=========================================================="
echo "⚙️  MariaDB Replication Setup (using mariadb-dump)"
echo "=========================================================="

# Function to execute SQL on host ports
run_sql() {
    local port=$1
    local query=$2
    mariadb -h 127.0.0.1 -P $port -u$USER -p$PASS -e "$query" -sN
}

echo "1. 🔍 Verifying Master Connectivity on Port $MASTER_PORT..."
if ! run_sql $MASTER_PORT "SELECT 1" > /dev/null; then
    echo "❌ Failed to connect to Master. Is MariaDB running on port $MASTER_PORT?"
    exit 1
fi
echo "✅ Master is reachable."

for port in $SLAVE1_PORT $SLAVE2_PORT; do
    echo -e "\n2. ⛓️  Initializing Slave on Port $port..."
    
    echo ">> Resetting Slave..."
    run_sql $port "STOP SLAVE;"
    run_sql $port "RESET SLAVE ALL;"
    
    echo ">> Dumping data from Master and piping to Slave (with --master-data=1)..."
    # We use sed to inject MASTER_HOST, MASTER_USER and MASTER_PASSWORD into the CHANGE MASTER TO command
    # generated by --master-data=1.
    mariadb-dump -h 127.0.0.1 -P $MASTER_PORT -u$USER -p$PASS \
        --all-databases \
        --master-data=1 \
        --single-transaction \
        --routines --triggers --events \
        | sed "0,/^CHANGE MASTER TO /s/^CHANGE MASTER TO /CHANGE MASTER TO MASTER_HOST='$MASTER_IP', MASTER_USER='$REPLI_USER', MASTER_PASSWORD='$REPLI_PASS', /" \
        | mariadb -h 127.0.0.1 -P $port -u$USER -p$PASS

    if [ $? -eq 0 ]; then
        echo "✅ Data sync and Master link successful for Port $port."
    else
        echo "❌ Failed to sync data or link Master for Port $port."
        continue
    fi
    
    echo ">> Starting Slave..."
    run_sql $port "START SLAVE;"
    
    echo ">> Checking Slave Status..."
    # Wait a bit for the IO thread to connect
    sleep 2
    IO_RUNNING=$(run_sql $port "SHOW SLAVE STATUS\G" | grep "Slave_IO_Running:" | awk '{print $2}')
    SQL_RUNNING=$(run_sql $port "SHOW SLAVE STATUS\G" | grep "Slave_SQL_Running:" | awk '{print $2}')
    
    if [ "$IO_RUNNING" == "Yes" ] && [ "$SQL_RUNNING" == "Yes" ]; then
        echo "✅ Slave on Port $port is UP and RUNNING"
    else
        echo "❌ Slave on Port $port has issues (IO: $IO_RUNNING, SQL: $SQL_RUNNING)"
        run_sql $port "SHOW SLAVE STATUS\G" | grep -E "Last_IO_Error|Last_SQL_Error"
    fi
done

echo -e "\n=========================================================="
echo "🏁 Replication Setup Finished"
echo "=========================================================="
