---
- name: Install MariaDB on Ubuntu
  hosts: all
  become: yes
  vars:
    mariadb_version: "10.6"

  tasks:
    - name: Remove existing MariaDB list files
      ansible.builtin.find:
        paths: /etc/apt/sources.list.d
        patterns: '*mariadb*.list'
        use_regex: true
      register: files_to_delete

    - name: Delete found files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"

    - name: Add MariaDB repository
      ansible.builtin.shell: "curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | bash"
      args:
        warn: false

    - name: Install MariaDB and related packages
      ansible.builtin.apt:
        name:
          - pv
          - python3
          - mariadb-client
          - mylvmbackup
          - mariadb-backup
          - mariadb-server
          - mariadb-plugin-cracklib-password-check
          - mariadb-plugin-connect
          - galera-arbitrator-4
          - cracklib-runtime
          - python3-cracklib
          - sysbench
          - tree
          - telnet
          - netcat-openbsd
          - netcat
          - libjemalloc2
          - libdbi-perl
          - libdbd-mysql-perl
          - rsync
          - nmap
          - lsof
          - pigz
          - git
          - pwgen
          - percona-toolkit
          - mycli
          - net-tools
          - nagios-nrpe-server
          - nagios-nrpe-plugin
          - centreon-plugins
          - monitoring-plugins
          - monitoring-plugins-contrib
          - nagios-snmp-plugins
        state: present
        update_cache: yes

    - name: Create /opt/local directory
      ansible.builtin.file:
        path: /opt/local
        state: directory
        mode: '0755'

    - name: Clone MySQLTuner-perl repository
      ansible.builtin.git:
        repo: https://github.com/major/MySQLTuner-perl.git
        dest: /opt/local/MySQLTuner-perl
        clone: yes
        update: yes

    - name: Set permissions for mysqltuner.pl
      ansible.builtin.file:
        path: /opt/local/MySQLTuner-perl/mysqltuner.pl
        mode: '0755'

    - name: Create profile script for mysqltuner
      ansible.builtin.copy:
        content: 'export PATH=$PATH:/opt/local/MySQLTuner-perl'
        dest: /etc/profile.d/mysqltuner.sh
        mode: '0755'

    - name: Restart unattended-upgrades service
      ansible.builtin.systemd:
        name: unattended-upgrades
        state: restarted
