---
  - name: "Update Ubuntu Distro"
    hosts: "{{ target | default('all') }}"
    gather_facts: true
    tasks:
      - name: "Update cache & Full system update"
        apt:
          update_cache: true
          upgrade: dist
          cache_valid_time: 3600
          force_apt_get: true
      - name: "Reboot After upgrade"
        reboot:
          reboot_timeout: 3600