# Set ip forwarding on in /proc and in the sysctl file and reload if necessary
- name: "[SYSCTL] Set ip forwarding on"
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: "[SYSCTL] set the maximum number of AIO operation files"
  ansible.posix.sysctl:
    name: fs.aio-max-nr
    value: 1048576
    sysctl_set: true
    state: present
    reload: true

- name: "[SYSCTL] set the maximum number of open files"
  ansible.posix.sysctl:
    name: fs.nr_open
    value: 1048576
    sysctl_set: true
    state: present
    reload: true

- name: "[SYSCTL] set swappiness"
  ansible.posix.sysctl:
    name: vm.swappiness
    value: 10
    sysctl_set: true
    state: present
    reload: true

- name: "[SYSCTL] set TCP keepalive time"
  ansible.posix.sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: 120
    sysctl_set: true
    state: present
    reload: true


- name: "[SYSCTL] set TCP keepalive reties"
  ansible.posix.sysctl:
    name: net.ipv4.tcp_keepalive_probes
    value: 4
    sysctl_set: true
    state: present
    reload: true

- name: "[SYSCTL] set TCP keepalive interval"
  ansible.posix.sysctl:
    name: net.ipv4.tcp_keepalive_intvl
    value: 20
    sysctl_set: true
    state: present
    reload: true
